---
title: "01: O problema do poeta - Solução básica"
subtitle: "Modelagem e solução do problema do poeta utilizando a formulação básica, sem generalização"
format:
  lumo-html: 
    # logo: "logo.png"                                     # Optional. Path to a logo displayed above the title
    github-repo: "https://github.com/maykongpedro/PO_O_Problema_Do_Poeta"        # Optional. Adds a github corner at the top right
    primary-color: "#69b3a2"
    self-contained: true
    is-particlejs-enabled: true                          # Optional: display interactive particles in the document header
    bg-image: ""                                         # Optional: link to an image for the header background
    code-fold: false     # <<<<<<<<<< SEMPRE MOSTRAR OS CÓDIGOS
    code-tools: true     # (opcional) botões p/ copiar
author: Maykon Pedro
date: last-modified
---

## Introdução

Nesse primeiro documento o problema será resolvido de maneira simplificada, alocando cada valor e restrição diretamente no código, sem pensar em escalonamento dos dados ou formulação genérica.

## Descrição do problema

Um poeta possui **40 ha de Pinus e 50 ha de floresta nativa**. Nos últimos 10 anos, o manejo do Pinus gerou **R\$ 36.000** com **800 dias de trabalho**, e o manejo da floresta nativa gerou **R\$ 60.000** com **1.500 dias de trabalho**.

Ele quer **maximizar a receita anual**, mas pode dedicar no máximo **180 dias/ano** ao manejo. Determine **quantos hectares de cada floresta** ele deve manejar por ano para obter a maior receita possível, respeitando os limites de área disponíveis.

::: column-margin
Esse é um enunciado simplificado do problema. A versão original pode ser consultada nos documentos do projeto.
:::

## Resumo dos dados

**Florestas**:

$$
\begin{aligned}
&\text{Pinus} = 40_{ha} \\
&\text{Nativa} = 50_{ha}
\end{aligned}
$$

**Receita anual por floresta:**

$$
\begin{aligned}
\text{Receita do Pinus}& = \text{R\$ } 36.000  \div  10_\text{anos} \div 40_{ha} \\
\text{Receita do Pinus}& = \text{R\$} 90_{ha/ano}
\end{aligned}
$$

$$
\begin{aligned}
\text{Receita da Nativa}& = \text{R\$ } 60.000  \div  10_\text{anos} \div 50_{ha} \\
\text{Receita da Nativa}& = \text{R\$} 120_{ha/ano}
\end{aligned}
$$

**Restrições de tempo de manejo por floresta:**

$$
\begin{aligned}
\text{Manejo do Pinus}& = 800_{dias}  \div  40_{ha} \div 10_\text{anos} \\
\text{Manejo do Pinus}& = 2_{dias/ha/ano}
\end{aligned}
$$

$$
\begin{aligned}
\text{Manejo de Nativa}& = 1500_{dias}  \div  50_{ha} \div 10_\text{anos} \\
\text{Manejo de Nativa}& = 3_{dias/ha/ano}
\end{aligned}
$$

## Formulação

### Índices/Conjuntos

### Parâmetros

### Variáveis de decisão

Pensando que a maximização da receita do Poeta está diretamente ligada ao preço recebido por floresta e à quantidade de hectares manejados, o item que pode ser alterado pensando no cenário ótimo, é a área a ser manejada para cada floresta. Sendo assim, as variáveis de decisão serão:

-   $x_1 \colon \text{número de hectares de floresta de Pinus a serem manejados}$
-   $x_2 \colon \text{número de hectares de floresta nativas a serem manejadas}$

### Função objetivo

Tendo como guia a maximização da receita anual (aqui chamaremos de Z), teremos que usar as receitas anualizadas para cada tipo de floresta (calculadas no tópico Resumo dos dados"). Assim, têm-se:

$\max z = 90x_1 + 120x_2$

A receita de pinus (R\$90 ha/ano) multiplicado pela área a ser manejada de pinus ($x_1$ ) irá gerar a receita total desse gênero. Somado isso com a receita da nativa (R\$120 ha/ano) multiplicado pela respectiva área, nos retorna a receita total das florestas do Poeta.

### Restrições

Devemos começar com a limitação de área para floresta, não temos como manejar mais hectares do que o disponível:

-   $x_1 ≤ 40 \text{ ha de floresta de Pinus}$
-   $x_2 ≤ 50 \text{ ha de floresta nativa}$

Após, precisamos checar no enunciado que o Poeta expressou sua vontade de não trabalhar mais que 180 dias por ano. Como calculamos o tempo gasto para cada floresta no tópico de resumo de dados, podemos chegar na seguint expressão matemática para representar a relação entre tempo de manejo x tempo máximo do poeta:

$$
2x_1 + 3x_2 \leq 180
$$

Sendo 2 dias/ha/ano para o pinus ($x_1$ ) e 3 dias/ha/ano para a nativa ($x_2$ ).

Para finalizar, devemos definir uma restrição que impeça o modelo de manejar áreas negativas:
$$
\begin{align*}
x_1 &\geq 0 \\
x_2 &\geq 0 
\end{align*}
$$

## Resolução do problema

### 0. Dados de entrada

```{python}
# dicionário de receita por tipo de floresta
receita = {"pinus": 90, "nativa": 120}

# dicionário de área máxima por tipo de floresta
area_max = {"pinus": 40, "nativa": 50}

# dicionário para limitar os recursos, no caso, o tempo de dias do poeta
recurso_max = {"tempo": 180}

# dicionário para controle do tempo gasto de manejo por floresta no ano
tempo_por_manejo = {"tempo": {"pinus": 2, "nativa": 3}}
```

### 1. Importar bibliotecas

```{python}
import pyomo.environ as pyo
```

### 2. Importar e definir solver

```{python}
# o executável foi instalado via terminal e o python consegue encontrá-lo nativaemente
# solver = pyo.SolverFactory("glpk")

# o executável foi baixado no computador
caminho_do_executavel = "C:/Users/klmp00145394/Documents/glpk-4.65/w64/glpsol.exe"
solver = pyo.SolverFactory(_name="glpk", executable=caminho_do_executavel)
```

### 3. Declarar modelo

```{python}
modelo = pyo.ConcreteModel()
```

### 4. Declarar índices, parâmetros e variáveis de decisão

### 4.1 Índices

Não utilizado nesse capítulo, pois trata-se de uma formulação direta.

### 4.2 Parâmetros

Não utilizado nesse capítulo, pois trata-se de uma formulação direta.

### 4.3 Variáveis de decisão

```{python}
modelo.x1_area_pinus = pyo.Var(within=pyo.NonNegativeReals)
modelo.x2_area_nativa = pyo.Var(within=pyo.NonNegativeReals)
```

### 5. Declarar função objetivo

```{python}
modelo.fo_z_receita = pyo.Objective(
  expr = receita['pinus'] * modelo.x1_area_pinus + receita['nativa'] * modelo.x2_area_nativa, 
  sense = pyo.maximize
)
```

### 6. Declarar restrições

```{python}
modelo.restricao_tempo_disp = pyo.Constraint(
  expr= 
  tempo_por_manejo['tempo']['pinus'] * modelo.x1_area_pinus + 
  tempo_por_manejo['tempo']['nativa'] * modelo.x2_area_nativa 
  <= recurso_max['tempo']
)

modelo.restricao_area_pinus = pyo.Constraint(expr=modelo.x1_area_pinus <= area_max['pinus'])

modelo.restricao_area_nativas = pyo.Constraint(expr=modelo.x2_area_nativa <= area_max['nativa'])
```

### 7. Resolver modelo

```{python}
# dando uma olhada na construção do modelo
modelo.pprint()
```

```{python}
# usando o solver para resolver o modelo
resultado = solver.solve(modelo)
```

### 8. Exportar resultados

```{python}
# resultados brutos do modelo
resultado.write
```

```{python}
# resultados organizados
print("\n===== RESULTADOS DO MODELO =====")
print(f"Status da otimização: {resultado.solver.status}")
print(f"Condição de término: {resultado.solver.termination_condition}")
print(f"Receita máxima (z) = R${pyo.value(modelo.fo_z_receita):.2f}")
print(f"Área manejada de Pinus (x1) = {modelo.x1_area_pinus.value:.2f} hectares")
print(f"Área manejada de Nativa (x2) = {modelo.x2_area_nativa.value:.2f} hectares")
```